export const lightTheme={
    palette: {
        themePrimary: '#0078d4',
        themeLighterAlt: '#eff6fc',
        themeLighter: '#deecf9',
        themeLight: '#c7e0f4',
        themeTertiary: '#71afe5',
        themeSecondary: '#2b88d8',
        themeDarkAlt: '#106ebe',
        themeDark: '#005a9e',
        themeDarker: '#004578',
        neutralLighterAlt: '#faf9f8',
        neutralLighter: '#f3f2f1',
        neutralLight: '#edebe9',
        neutralQuaternaryAlt: '#e1dfdd',
        neutralQuaternary: '#d0d0d0',
        neutralTertiaryAlt: '#c8c6c4',
        neutralTertiary: '#a19f9d',
        neutralSecondary: '#605e5c',
        neutralPrimaryAlt: '#3b3a39',
        neutralPrimary: '#323130',
        neutralDark: '#201f1e',
        black: '#000000',
        white: '#ffffff',
  }
}

export const darkTheme ={
    palette: {
        themePrimary: '#f2f2f2',
        themeLighterAlt: '#f4f4f4',
        themeLighter: '#f5f5f5',
        themeLight: '#f6f6f6',
        themeTertiary: '#f8f8f8',
        themeSecondary: '#f9f9f9',
        themeDarkAlt: '#fbfbfb',
        themeDark: '#fcfcfc',
        themeDarker: '#fdfdfd',
        neutralLighterAlt: '#070707',
        neutralLighter: '#070707',
        neutralLight: '#070707',
        neutralQuaternaryAlt: '#070606',
        neutralQuaternary: '#060606',
        neutralTertiaryAlt: '#060606',
        neutralTertiary: '#c8c8c8',
        neutralSecondary: '#d0d0d0',
        neutralPrimaryAlt: '#dadada',
        neutralPrimary: '#ffffff',
        neutralDark: '#f4f4f4',
        black: '#f8f8f8',
        white: '#080808',
    }
}